apiVersion: batch/v1
kind: CronJob
metadata:
  name: pod-restarter
spec:
  schedule: "@daily"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: pod-restarter
            image: bitnami/kubectl:latest
            command: ["kubectl", "rollout", "restart", "deployment/v-deploy"] # Change name of Deployment
          restartPolicy: Never
          serviceAccountName: pod-restarter

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-restarter
automountServiceAccountToken: true

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: pod-restarter
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "patch"]
  
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-restarter
  namespace: default
subjects:
- kind: ServiceAccount
  name: pod-restarter
  apiGroup: ""
roleRef:
  kind: Role
  name: pod-restarter
  apiGroup: ""